# Generated by Django 4.1.2 on 2022-11-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("add", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favrioute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_favrioute",
                        to="add.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_favrioute",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "owner")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="favrioute",
            field=models.ManyToManyField(
                related_name="user_category_favrioute",
                through="add.Favrioute",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
