# Generated by Django 4.1.2 on 2023-04-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("add", "0002_add_add_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add",
            name="add_history",
        ),
    ]
