# Generated by Django 4.1.2 on 2023-04-20 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.BinaryField(
                        blank=True, editable=True, max_length="max", null=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="The MIMEType of the file",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile_photo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
