# Generated by Django 4.1.2 on 2022-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerprofilephoto",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="The MIMEType of the file",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ownerprofilephoto",
            name="picture",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
